[package]
name = "src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encedeus_js_runtime = "0.1.0-alpha"
include_dir = "0.7.3"
